README.md

The svg path was wrong, however the correct path seems to show that it's disabled. Proof:

Greenkeeper SVG path

---

src/index.js
src/object.js
test/objects.spec.js

compareDeep should be ==

---

CHANGELOG.md
package.json

Greenkeeper updated [babel-loader](https://github.com/smartprocure/futil-js/pull/81) and [danger-js](https://github.com/smartprocure/futil-js/pull/80) in recently merged pull requests.

v1.11.1 thanks to Greenkeeper

---

CHANGELOG.md
README.md
package.json
src/object.js
test/objects.spec.js

Add `unflattenObject` and warn about `mapProp` deprecation in favor of lodash `_.update`

`unflattenObject` and `mapProp` deprecation

---

CHANGELOG.md
package.json
webpack.config.js

This is to avoid regeneratorRuntime errors for consumers

add babel-polyfill now that we are using async for aspects

---

CHANGELOG.md
package.json
src/aspect.js
test/aspect.spec.js
webpack.config.js

`babel-polyfill` was required to use async/await here with an app using create-react-app, but we can't have it loaded twice. `futil-js` can just the promise api for now

convert aspect async to promises and rip out babel-polyfill

---

CHANGELOG.md
README.md
package.json
src/aspect.js

The previous implementation assumed that before/after were synchronous and also didn't throw

Add support async before and after to aspect

---

CHANGELOG.md
package.json
src/aspect.js

IE would break if using a deprecated futil function—this fixes that.

Prevent IE from breaking on deprecate

---

CHANGELOG.md
package.json

Makes duti use `latest` instead of pinning to a version.

Update duti to latest

---

CHANGELOG.md
package.json
src/regex.js

A faster `matchAnyWord` function.
Changed it as per the previous change to `matchAllWords` https://github.com/smartprocure/futil-js/pull/138

Fix for issue: https://github.com/smartprocure/futil-js/issues/142

---

.circleci/config.yml
CHANGELOG.md
README.md
package.json
src/array.js
src/object.js
test/objects.spec.js

flattenObject is flattening empty arrays in the wrong way, the result of
it is that empty arrays appear to be simple objects. The reason this is
happening is because we're trusting on `dotJoin`, which uses `compact`,
which by definition removes zeroes from the array.
My solution is simply to add another `dotJoin` that allows zeroes. I'm
naming it `dotJoinWith`, since it accepts a function that will be used
to select how to filter the array.

flattenObject fix

---

.circleci/config.yml

So that we can merge greenkeeper pull requests for dev dependencies into master without having to upgrade.

Ignoring npm publish errors

---

CHANGELOG.md
README.md
package.json
src/object.js
test/objects.spec.js

Similar to `_.matches`, except it returns true if 1 or more object properties match instead of all of them. See https://github.com/lodash/lodash/issues/3713.

Add matches some

---

README.md

The function signature for `unless` seems to be copied from the `when` above it in README.md. It should use `onFalse` instead of `onTrue`

Update unless function signature in readme

---

CHANGELOG.md
package.json
src/index.js
test/init.js
test/misc.spec.js
webpack.config.js

closes #146 
I decided to use the built-in Define plugin in Webpack as it doesn't add any external dependency and is just enough for the desired behaviour.
It simply defines a macro (picked __VERSION__ to minimise the risk of name collision in the future) with the version found in `package.json` at build time. That macro is then exported by the package's index as a named constant `VERSION`.
I had to slightly tweak the test script to require a file before the tests run that initialises a mock `__VERSION__` so we can assert that the correct value is being exported.

Inject package version during the build and expose it at runtime

---

CHANGELOG.md
README.md
package.json
src/array.js
src/index.js
src/iterators.js
src/string.js
test/array.spec.js
test/iterators.spec.js
test/string.spec.js

`(((acc, i, xs) -> a), (acc, i, xs) -> a) -> (acc, i, xs) -> a` used
to generate an iterator that will answer with the result of the first
given iterator for all of the properties of the iterated list except
for the last one, which will be answered with the result of the second
given iterator.
`(f, array) -> array` `(f, array) -> array` The function `f` is treated as an iterator, so
it will receive the accumulator, the current index and the full array.
The result of the function is added right before the current element
of the iteration. Produces a new array with the changes.
**Note:** Intersperse can be used with JSX components! Specially with
the `differentLast` iterator:
Example with words:
```
> F.intersperse(differentLast(() => 'or', () => 'or perhaps'), ['first', 'second', 'third']) …
```

toSentence & intersperse

---

.circleci/config.yml
CHANGELOG.md
README.md
karma.conf.js
package.json
src/lens.js

Given that React is so popular, export a utility function to convert a
`useState` call to a lens

New lens helper for React users

---

CHANGELOG.md
README.md
package.json
src/object.js
test/objects.spec.js

F.renameProperty had two issues:
1. The function was not pure meaning it had side effects.
2. The function was adding the property to be replaced to the returned object if the property did not exist.

Purify renameProperty

---

CHANGELOG.md
package.json
src/regex.js

Fixes #273 
* since we want "match all words" and "match any words" functionality elsewhere and aren't always in a position to accept a match from Futil itself it's best to export these functions.
* in the current case I'll use this both in the `contexture-mongo` `filter` component and in a project that needs a contexture type that involves any-word regex matching

feature/273 - export word match regex builders

---

CHANGELOG.md
package.json
src/regex.js

fixes #275 
* that extra `.*`s mean the reported match will be the full input string rather than the leading null string. the generated regexes are extensionally equivalent (e.g. they'll always give the same answer with `RegExp.test`)

Update all words regex generator to match full string rather than initial empty string

---

CHANGELOG.md
README.md
package.json
src/object.js
test/objects.spec.js

Graduating from [contexture-react's `utils` folder](https://github.com/smartprocure/contexture-react/blob/b3c45ca05ab470be00972a2068ba93ea02dc3159/src/utils/futil.js#L17) to its own spot in the futil library 🤗

Add `mergeOverAll`

---

CHANGELOG.md
README.md
package.json
src/object.js
test/objects.spec.js

Fixes #281
The last commit adds partial autocurrying (and tests) to `mergeOverAll`, such that it supports `([f, g], ...args)` in addition to `([f, g])(...args)`. Not part of the issue, but seemed like it'd be nice to have. 🙂

use `mergeAllArrays` in `mergeOverAll` and allow uncurried usage

---

CHANGELOG.md
README.md
package.json

This has been bothering me - the description was super vague about how the predicate should work, and it didn't help that our function signature was wrong (the first argument of the predicate should be `[a]`, not `a`). Hopefully it's much clearer now 🙂

Clarify `chunkBy` description

---

CHANGELOG.md
package.json
src/lens.js
test/lens.spec.js

also more colorful tests 🎨
note: the prototype case does indeed fail when `_.has` is used in `targetBinding` instead of `_.hasIn`

Fix targetBinding for synthetic events

---

CHANGELOG.md
README.md
package.json
runkit.example.js
src/array.js
src/collection.js
src/conversion.js
src/lens.js
src/logic.js
src/object.js
src/regex.js
src/string.js
src/tree.js
test/array.spec.js
test/collections.spec.js
test/lens.spec.js
test/logic.spec.js
test/regex.spec.js
test/string.spec.js
test/tree.spec.js

`onMouseEnter`/`onMouseLeave` are more consistent with the notion of "hovering" state on a DOM element, since they don't bubble the cursor events to children. With `onMouseOver`/`onMouseOut`, hovering over a child of the element can interfere with the event, which is probably not the behavior we want for `domLens.hover`.
https://javascript.info/mousemove-mouseover-mouseout-mouseenter-mouseleave#mouseout-when-leaving-for-a-child

Use onMouseEnter/Leave in domLens.hover

---

CHANGELOG.md
README.md
package.json
src/regex.js
test/regex.spec.js

- Add support for regular expression arguments to `highlight`
- Force global and case-insensitive matches on `postings` (for parity with `postingsForWords`)
- Clarify `highlight` description in README
- Add description for `postingsForWords` to README

Highlight stuff

---

CHANGELOG.md
package.json
src/tree.js

- Kill promises in `findIndexedAsync` to fix regeneratorRuntime shenanigans
This is some gnarly code 😅
We're going to need to overhaul the webpack build process at some point so we can safely use `async` in `futil` 😰 
My apologies to all other `futil` contributors 😂

kill promises in findIndexedAsync

---

CHANGELOG.md
package.json
src/tree.js
test/tree.spec.js

- Allow `walkAsync` to handle non-async traversals

Allow `walkAsync` to handle non-async traversals

---

CHANGELOG.md
README.md
package.json
src/object.js
test/objects.spec.js

- Adds `unwindArray`, an alias for flatMapping `unwind` (this really just exists to document that `unwind` itself doesn't act on arrays, as we'd expect it to based on mongo's `$unwind` behavior)
- Updates `unwind` to call `_.castArray` so that it only unwinds arrays (not strings) - this is a potentially breaking change, but the behavior on strings wasn't documented and I'd argue that it wasn't intended, so it should be ok
- Adds extra stories for `unwind` to document edge cases (e.g. that the behavior for both nonexistent keys and keys whose values are not unwindable is to return an empty array)

Unwind things

---

CHANGELOG.md
README.md
package.json

Before this change the code examples in the README
were not valid syntax

Added single quotes to make import statement valid

---

README.md

This PR proposes to link to [loadash/fp](https://github.com/lodash/lodash/wiki/FP-Guide) in the initial mention of it in the README. 
-----------
Sidenote: I made a [PR](https://github.com/stoeffel/awesome-fp-js/pull/99#issue-385214301) on the official "awesome functional programming javascript" repo (4.7k+ stars) to add futil-js to the list.

Add link to lodash/fp

---

README.md

Prepare the readme file for the new docs site (standardize format, etc) which generates this file.
Some things done here:
- Place method signatures on their own line
- Wrap all examples in ```js
- Standardize note formatting
- Flatten fourth level things (e.g. aspect methods)
- Update and expand lodash conversion docs
- Move `isPromise` docs to `lang`
- Add some missing signatures
- Lots of other small tweaks

New Doc Site Readme Prep

---

src/array.js
src/aspect.js
src/collection.js
src/conversion.js
src/function.js
src/index.js
src/iterators.js
src/lang.js
src/lens.js
src/logic.js
src/object.js
src/regex.js
src/string.js
src/tree.js

This is another prep PR for the new docs site - the readme and docs site will be generated from JSON which is generated from inlined jsdoc comments.
The next PR will rearrange the source and/or readme to get them aligned in the same order

Add jsdocs inline for all documented methods

---

README.md

Rearranged the readme to align with source code order (and fixed a few documentation errors like singleObjectE which is actually singleObjectR as well as a few tree methods named incorrectly in the readme)

reorder the readme to align with source code order

---

CHANGELOG.md
package.json
test/array.spec.js
test/aspect.spec.js
test/collections.spec.js
test/conversions.spec.js
test/function.spec.js
test/iterators.spec.js
test/lang.spec.js
test/lens.spec.js
test/logic.spec.js
test/misc.spec.js
test/objects.spec.js
test/regex.spec.js
test/tree.spec.js

- Replaced `eql` for `deep.equal`
- Replaced all unnecessary `deep.equal` assertions with `.equal`
- Replaced `to.equal(true)` and `to.equal(false)` with `to.be.true` and `to.be.false`. Currently, both types can be found across the tests.

minor standardization effort

---

.circleci/config.yml
CHANGELOG.md
package.json

- Explicitly build the code in CI so it gets published with the lib folder no matter what.

Explicit Build Step in CI

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/array.js
src/string.js
test/array.spec.js
test/string.spec.js

- Add `keysToObject`
- Change `wrap` and dependents like `parens` to support empty content better (and remove weird "feature" where post would default to pre if falsey). Potentially a breaking change, but that behavior was extremely weird and there were no known usages.
- Curry `moveIndex`

Small functions

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/async.js
src/index.js
src/tree.js
test/async.spec.js

Long overdue. `flowAsync` is magical. You can mix and match sync and async, automatically get `Promise.all` and `promiseProps` for arrays and objects, and it'll stay sync if nothing is async (e.g. you don't need to await if nothing is async).
`flowAsyncDeep` is even more magical. It uses the new `resolveOnTree` method to resolve deep tree structures, so it will work even if you're doing really deep promises (e.g. using an async iteratee in `_.update` deep in your structure). It's a separate method because traversing the entire object graph is a performance tradeoff we think is worth surfacing to end users. It's possible that we'll deprecate it and make it the default behavior for `flowAsync` in a future release if the performance hit is generally not noticeable.
- Add `flowAsync` and …

`flowAsync`

---

CHANGELOG.md
package-lock.json
package.json
src/array.js
src/string.js
test/array.spec.js
test/string.spec.js

Fixes a number of edge cases
- [Make `intersperse` handle more edge cases (undefined, null, stirngs, objects, etc)](https://github.com/smartprocure/futil-js/commit/e8ee29b0f1f57ca8215571b66bd09c9080225583)
- [Improve `toSentence` edge cases (mostly from improving intersperse, but also by making strings less surprising)](https://github.com/smartprocure/futil-js/commit/81da317168c46372a10471b3f492a5369b0fc9cd)

Fix `intersperse` and `toSentence`

---

CHANGELOG.md
README.md
package-lock.json
package.json
scripts/generate-docs.js
src/array.js
src/collection.js
src/conversion.js
src/object.js
src/string.js
src/tree.js
test/array.spec.js
test/collections.spec.js
test/objects.spec.js
test/string.spec.js

- Add `renamePropertyOn`, `unsetProperty`
- Add `updateOwn`, `updateOwnOn`, `updateSome`, `updateSomeOn`, `updateAll`, `updateAllOn`
- Add `crunchWhitespace`
- Export `writeTreeNode`
- Add `chunkByValue`
- Pass indexes to `arrayToObject`
- Add `omitByIndexed` conversion
Also begin adding `@since` and `@type` in jsdoc (preparing for proper TS typing:)

More methods

---

.changeset/weak-yaks-burn.md
src/tree.js

Use `pushOn` instead of `push` to avoid creating temporary arrays when traversing the tree.

Improve performance of treeToArrayBy and leavesBy

---

.changeset/poor-toys-grin.md
package.json
runkit.example.js
yarn.lock

We decided to publish this package under `futil` and stop publishing `futil-js` but we had not changed the name in `package.json` so we were publishing the wrong name.

Publish under futil name instead of futil-js
