smartprocure/futil-js

package.json
test/array.spec.js
test/collections.spec.js
test/flipped.spec.js
test/misc.spec.js
test/mocha.opts
test/mutables.spec.js
test/objects.spec.js

Running tests and coverage against src, not lib

---

CHANGELOG.md
package.json

Add prepublish and bump package

---

.eslintrc.js
test/.eslintrc.js

Here I'm using the default rules available in https://github.com/jfmengels/eslint-plugin-lodash-fp 's readme, they work out of the box!  :)
I also separated mocha 🕺

Using lodash-fp, moving mocha eslint rules to the test folder

---

src/conversion.js
src/object.js
test/array.spec.js
test/collections.spec.js
test/conversions.spec.js
test/flipped.spec.js
test/misc.spec.js
test/mutables.spec.js
test/objects.spec.js

Since this is a small library, I want it to look as pretty as it can be 👀 which means a bunch of personal preferences and whimsical changes. Please pick those who you might like.

Style polishes perhaps! Please review

---

CHANGELOG.md
package.json
src/object.js
test/objects.spec.js

compareDeep was good as ===

---

README.md
package.json
src/index.js
test/algebras.spec.js
test/trees.spec.js

New function: ~deepSearch~ ~depthMap~ ~fold~ ~rmap~ **deepMap**

New function: deepMap

---

src/object.js
test/algebras.spec.js
test/misc.spec.js
test/objects.spec.js

Includes:
- Missing tests.
- Better deepMap test for Sets, this time immutable and works with
babel-core/register

100% test coverage

---

webpack.config.js

webpack 2 spaces

---

CHANGELOG.md
circle.yml
dangerfile.js
package.json

WIP Testing CI stuff, also testing danger-js

---

CHANGELOG.md
README.md
package.json
src/function.js
test/misc.spec.js

As thought on the _other_ project.
Here's the definition I'm thinking: `(a, Monoid f) -> f[a] :: f a`
Please review 🙇

Added boundMethod

---

CHANGELOG.md
package.json
src/conversion.js

noCap mapValues

---

CHANGELOG.md
README.md
package.json
src/lens.js
test/lens.spec.js

Add missing `views` lens function (counterpart to `sets`)

add missing `views` lens function

---

CHANGELOG.md
README.md
package.json
src/aspect.js

So you have access to everything at all points

Pass params to after and onError

---

CHANGELOG.md
package.json
src/index.js

f.map should be uncapped 👀

---

CHANGELOG.md
README.md
package.json
src/aspect.js

Like `errors`, but just one field instead of an array

Add new error aspect example

---

CHANGELOG.md
README.md
package.json
src/conversion.js

add mutable set

---

CHANGELOG.md
README.md
package.json
src/index.js
test/misc.spec.js

Useful to clean all the string properties of something before passing it through.

trimStrings

---

CHANGELOG.md
package.json
src/aspect.js
test/aspect.spec.js

Fix unit tests.

---

CHANGELOG.md
package.json

Feature update webpack 3.0.0

---

CHANGELOG.md
package.json

Upgrade danger to 0.19.0

---

CHANGELOG.md
README.md
package.json
src/conversion.js
src/object.js
test/objects.spec.js

Like `cascade` but only if the property actually exists. Accepts falsey values.

cascadeProp

---

.circleci/config.yml
CHANGELOG.md
package.json

Use new config for gooder speedings
Reduce build times by about 2-2.5 minutes :smile_cat:

Use Circle CI 2.0

---

CHANGELOG.md
package.json
src/object.js
test/objects.spec.js

Fix for diff functions to properly ignore things that didn't change.

Fix for diff functions to properly ignore things that didn't change

---

CHANGELOG.md
package.json
src/regex.js

The current one is 75% slower, according to jsperf:
https://jsperf.com/matchallwords

matchAllWords optimized for speed

---

.circleci/config.yml
CHANGELOG.md
package.json

Always run duti

---

CHANGELOG.md
package.json
src/array.js

Curried Push

---

CHANGELOG.md
README.md
package.json
src/object.js

new "pickOn" object utility that mutates the object

New "pickOn" object utility that mutates the object

---

CHANGELOG.md
README.md
package.json
src/object.js
test/objects.spec.js

diff and diffArray

---

CHANGELOG.md
package.json
src/regex.js

Non-urgent, I'll add the changes to the README/Changelog after you merge the diff PR @daedalus28

Curry-ing postings/highlight functions

---

.circleci/config.yml

Ignore master branch for cross browser testing.

Do not run browser tests for master branch.  Thanks @sean-clayton

---

CHANGELOG.md
package.json

Single PR for all the greenkeeper PRs so we bump up the version once

---

CHANGELOG.md
README.md
package.json

From standard to prettier.

---

CHANGELOG.md
package.json
src/tree.js

Tree Lookup's inside function should be curried

---

package.json

chore(package): update eslint to version 4.18.0

---

CHANGELOG.md
package.json
src/conversion.js

1.43.0 pickByIndexed and a better conversion file

---

CHANGELOG.md
package.json
src/conversion.js

I guess I was tired last night 🌚

Fixed wrong reference on conversions.js

---

CHANGELOG.md
package.json
webpack.config.js

I'm making this PR to test some dependencies upgrades.
Closes #209
Closes #207 
Closes #206 
Closes #201 
Closes #190

Dependencies upgrade

---

CHANGELOG.md
karma.conf.js
package.json
webpack.config.js

Webpack 4 has a bug. See: https://stackoverflow.com/a/49119917

1.43.3 Fixed futil-js for NodeJS

---

CHANGELOG.md
README.md
package.json
runkit.example.js

Add Runkit examples

---

.circleci/config.yml
CHANGELOG.md
package.json
src/array.js
src/index.js
src/logic.js
src/object.js
src/regex.js
src/string.js
src/tree.js
test/misc.spec.js
test/tree.spec.js
webpack.config.js

I think I fixed the version issue.

---

CHANGELOG.md
package.json
src/array.js
src/collection.js
src/string.js
test/string.spec.js

fix autoLabelOption

---

CHANGELOG.md
README.md
package.json
src/string.js
test/string.spec.js

Adds `uniqueString`, which deduplicates strings, and for good measure, `uniqueStringHash`, which manages multiple `uniqueString`s.
I'm not very familiar with writing functions in this style, so I might have gone a little overboard with it 😅

Add `uniqueString`

---

CHANGELOG.md
README.md
package.json
src/collection.js
test/collections.spec.js

Add compactMap

---

CHANGELOG.md
README.md
package.json
src/object.js
test/objects.spec.js

Fresh new object utils (from contexture-react) ✨

Add getWith, expandObject, and expandObjectBy

---

CHANGELOG.md
README.md
package.json
src/logic.js
test/logic.spec.js

Fixes #284 
Just needs tests, readme update, etc

Better currying for `logic` methods

---

CHANGELOG.md
package.json
src/array.js
test/array.spec.js

handle empty & undefined values in chunkBy

---

CHANGELOG.md
package.json
src/object.js

This will make it so we can compare objects like dates

Use deep comparison in F.{simple,}diff

---

CHANGELOG.md
README.md
package.json

Fix isBlank docs

---

CHANGELOG.md
README.md
karma.conf.js
package.json
src/logic.js
test/logic.spec.js

Logic functions behave unpredictably with `undefined` as predicate #311

---

CHANGELOG.md
README.md
package.json
src/tree.js
test/tree.spec.js

Add `mapTree`, `mapTreeLeaves` 😎

Add `mapTree`, `mapTreeLeaves`

---

CHANGELOG.md
package.json
test/conversions.spec.js
test/lang.spec.js
test/logic.spec.js
test/regex.spec.js

This PR changes f. to F. in the test files.

changed all f. to F.

---

CHANGELOG.md
package.json
test/array.spec.js

Added a test or two
Moved some tests around to match the original file order
Tweaked a couple of tests a bit for clarity

array tests

---

CHANGELOG.md
package.json
test/lang.spec.js

- Finished lang tests
- This PR has a different test for tapError that doesn't use the console.log

Lang tests4

---

CHANGELOG.md
package.json
test/logic.spec.js

finished logic tests

---

CHANGELOG.md
package.json
test/function.spec.js

Finished function tests.
- Organized and added tests.

Function tests

---

CHANGELOG.md
package.json
test/string.spec.js

- Just moved a test from the bottom to the middle of the file to match the code file.

finished string tests

---

CHANGELOG.md
package.json
test/function.spec.js
test/lang.spec.js
test/misc.spec.js

Removed basic functions tests from the misc.spec file and moved them to function.spec file.

finished misc tests

---

.circleci/config.yml
docs/beta/package.json
package.json

Deploys the new docs site to github-pages on push to master

Deploy docs site

---

.circleci/config.yml

bump circleci node image

---

.circleci/config.yml

tweak deploy action

---

CHANGELOG.md
docs/beta/src/App.tsx
docs/beta/src/components/GSSinglePageLayout/ResponsiveBasicLayout.tsx
docs/beta/src/components/header/Header.tsx
package.json

After showing this to Sam, the change in this PR was brought up. There was a misunderstanding with the header display on the home page. 
Based on a misunderstanding I added the header to the home page instead of removing a header that was present with nothing inside. This header is no longer present on the Home view per this PR. I also cleaned up  previous changes no longer needed.

Fix Home Display

---

CHANGELOG.md
package-lock.json
package.json
scripts/generate-readme.js
src/array.js
src/aspect.js
src/object.js
src/string.js
src/tree.js

Fixes #405 
- Generate readme in CI
- Tweak code docs to better align to formatted readme

Generate Readme During CI

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/tree.js
test/tree.spec.js

Add tree find

---

CHANGELOG.md
docs/beta/src/utils/filterDocs.ts
package.json

Modifies regex to allow for case insensitive searching

Enable Case Insensitive Searching

---

.changeset/big-plums-wave.md
src/array.js
src/collection.js
src/string.js
src/tree.js
test/tree.spec.js

Use an internal only function for now and add comments on the other functions to remember to change in the next major.

Do not remove zeroes from tree paths
